 select DISTINCT T1.M_CREATION, 0 as DYNAMIC_TABLE_CATEGORY from DYNDBF1#TRN_DYND_DBF T1, DYNDBF2#TRN_DYNF_DBF T2 where T1.M_CREATION=T2.M_CREATION AND T1.M_F_SVCMP=1 AND T1.M_F_CMPNO=0 AND M_CLASS LIKE 'DYN_TRNRP%' AND T2.M_FLD_LABEL NOT LIKE 'S_%'
union all
 select DISTINCT T1.M_CREATION, 2 as DYNAMIC_TABLE_CATEGORY from DYNDBF2#TRN_DYND_DBF T1, DYNDBF2#TRN_DYNF_DBF T2 where T1.M_CREATION=T2.M_CREATION AND T1.M_F_SVCMP=1 AND T1.M_F_CMPNO=0 AND M_CLASS LIKE 'DYN_TRNRP%' AND T2.M_FLD_LABEL NOT LIKE 'S_%'
union all
 select DISTINCT T1.M_CREATION, 1 as DYNAMIC_TABLE_CATEGORY from DYNDBF3#TRN_DYND_DBF T1, DYNDBF2#TRN_DYNF_DBF T2 where T1.M_CREATION=T2.M_CREATION AND T1.M_F_SVCMP=1 AND T1.M_F_CMPNO=0 AND M_CLASS LIKE 'DYN_TRNRP%' AND T2.M_FLD_LABEL NOT LIKE 'S_%'
union all
 select DISTINCT T1.M_CREATION, 3 as DYNAMIC_TABLE_CATEGORY from DYNDBF4#TRN_DYND_DBF T1, DYNDBF2#TRN_DYNF_DBF T2 where T1.M_CREATION=T2.M_CREATION AND T1.M_F_SVCMP=1 AND T1.M_F_CMPNO=0 AND M_CLASS LIKE 'DYN_TRNRP%' AND T2.M_FLD_LABEL NOT LIKE 'S_%'